export const maintenanceTopics=[
  {id:'bearings',discipline:'Mechanical',title:'Bearings',purpose:'Support rotating shafts with controlled friction and alignment.',inspect:['Noise, vibration and temperature trend','Lubricant type, quantity and contamination','Fit, clearance, alignment and housing condition'],failures:['Lubrication starvation or over-greasing','Misalignment, looseness or incorrect fit','Water/dust ingress and electrical fluting'],plan:['Confirm bearing number, clearance, seals and cage','Keep matched bearing, locknut/washer and correct grease','Plan puller/heater, alignment tools and cleanliness controls']},
  {id:'hydraulic-valves',discipline:'Mechanical',title:'Hydraulic valves',purpose:'Control pressure, direction and flow in hydraulic circuits.',inspect:['Leakage, pressure drop and spool response','Oil cleanliness and filter differential pressure','Solenoid voltage, coil heat and manual override'],failures:['Contamination sticking the spool','Seal leakage or worn seat','Incorrect pressure setting or failed coil'],plan:['Record make, model, port size and pressure range','Stock seal kit, coil and critical cartridge/valve','Isolate and depressurize; cap every opened line']},
  {id:'pumps',discipline:'Mechanical',title:'Pumps',purpose:'Provide flow and pressure for water, oil, emulsion or process circuits.',inspect:['Suction condition, discharge pressure and flow','Vibration, bearing temperature and seal leakage','Coupling alignment, cavitation noise and motor current'],failures:['Dry running/cavitation','Seal or bearing failure','Erosion, blocked suction or wrong rotation'],plan:['Verify duty point, fluid, seal and material of construction','Keep seal kit, bearings, coupling element and critical pump','Plan priming, alignment and post-start pressure checks']},
  {id:'cylinders',discipline:'Mechanical',title:'Hydraulic & pneumatic cylinders',purpose:'Convert fluid pressure into controlled linear motion.',inspect:['Rod scoring, seal leakage and drift','Mounting pins, bushes and alignment','Stroke, cushioning and operating pressure'],failures:['Worn seals or damaged rod','Side loading and bush wear','Contaminated fluid or damaged barrel'],plan:['Confirm bore, rod diameter, stroke and mounting','Keep seal kit, rod seal, wiper, pins and bushes','Support load, isolate pressure and set alignment']},
  {id:'shafts',discipline:'Mechanical',title:'Shafts',purpose:'Transmit torque and maintain alignment between rotating components.',inspect:['Runout, wear at bearing/seal seats and cracks','Keyway, spline, thread and shoulder condition','Alignment, balance and coupling fit'],failures:['Fatigue at stress concentration','Fre007ting/loose fit and misalignment','Overload, bending or corrosion'],plan:['Record drawing, material, heat treatment and tolerances','Verify keys, sleeves, nuts and mating bearings','Plan NDT, runout check and balance where required']},
  {id:'couplings',discipline:'Mechanical',title:'Couplings',purpose:'Transmit torque while accommodating limited misalignment.',inspect:['Alignment, element wear, bolt tightness and guard','Lubrication for geared/grid types','Hub fit, backlash and abnormal vibration'],failures:['Poor alignment','Element fatigue or lubrication loss','Loose fasteners and overload'],plan:['Confirm type, size, bore, keyway and rating','Keep flexible element/grid, bolts and seals','Laser-align and record final readings']},
  {id:'pipes',discipline:'Mechanical',title:'Pipes, hoses & fittings',purpose:'Carry process water, air, oil, emulsion and hydraulic fluid safely.',inspect:['Leaks, corrosion, abrasion and hose cracking','Supports, clamps, bend radius and vibration','Pressure rating, connection type and contamination'],failures:['Burst from ageing or pressure spikes','External rubbing and poor routing','Wrong material/seal or loose connection'],plan:['Record size, schedule, material, pressure and end connection','Keep correct hose/fittings, clamps and compatible seals','Drain, depressurize, flush and leak-test']},
  {id:'seals',discipline:'Mechanical',title:'Seals & seal kits',purpose:'Retain lubricant/fluid and exclude contamination at static and moving joints.',inspect:['Leak path, shaft/rod surface and housing damage','Seal orientation, material and operating temperature','Pressure, speed and fluid compatibility'],failures:['Wrong material or installation damage','Worn mating surface/misalignment','Heat, pressure spike or contamination'],plan:['Use OEM kit or verify every dimension and elastomer','Store clean, dark and within shelf-life controls','Replace mating wear parts and lubricate during assembly']},
  {id:'motors',discipline:'Electrical',title:'Electric motors',purpose:'Convert electrical power into mechanical drive torque.',inspect:['Current balance, insulation resistance and winding temperature','Bearing vibration, cooling path and terminal tightness','Alignment, load condition and start history'],failures:['Bearing/lubrication failure','Overload, phase imbalance or insulation breakdown','Blocked cooling and misalignment'],plan:['Record kW, voltage, frame, poles, speed, mounting and duty','Keep bearings, fan, terminal parts and critical complete motor','Plan isolation, cable checks, alignment and no-load rotation test']},
  {id:'sensors',discipline:'Electrical',title:'Sensors & switches',purpose:'Detect position, pressure, temperature, flow, level or speed for control and protection.',inspect:['Signal stability, calibration and sensing gap','Cable/connector condition and environmental protection','PLC indication, interlock action and bypass status'],failures:['Contamination or incorrect gap','Cable damage, loose connection or moisture ingress','Drift, wrong range or power-supply fault'],plan:['Record type, range, output, supply, thread and connector','Keep critical sensor plus cable/connector','Prove trip/interlock after replacement; remove bypasses']},
  {id:'electrical-valves',discipline:'Electrical',title:'Solenoid & control valves',purpose:'Convert electrical commands into pneumatic or hydraulic control action.',inspect:['Coil voltage/current, response and manual override','Air/oil quality, spool movement and leakage','Connector, suppression device and PLC output'],failures:['Burnt coil or wrong voltage','Sticking spool from contamination','Low pilot pressure or damaged seals'],plan:['Confirm valve model, function, ports, voltage and connector','Keep coil, connector, seal kit and critical valve','Test local operation and control-system feedback']},
  {id:'cables',discipline:'Electrical',title:'Power & control cables',purpose:'Carry power and signals reliably between panels, field devices and motors.',inspect:['Insulation damage, gland sealing and bend radius','Termination tightness, heating and earth continuity','Shielding, segregation and cable identification'],failures:['Mechanical damage or moisture ingress','Loose/high-resistance termination','EMI, wrong cable type or overload'],plan:['Record cores, size, voltage, shielding, armour and length','Keep glands, lugs, ferrules and critical cable lengths','Insulation-test, phase-check and verify earthing']},
  {id:'plc',discipline:'Electrical',title:'PLC, I/O & control panels',purpose:'Execute control logic, interlocks, sequencing and equipment protection.',inspect:['Active alarms, diagnostics and forced/bypassed signals','Power supply, panel temperature, fans and filters','I/O health, network status, terminals and backups'],failures:['Power-supply or module failure','Loose terminals, heat, dust or communication loss','Program/configuration change without backup'],plan:['Maintain current program, hardware configuration and backups','Keep critical PSU, CPU/I/O/module and communication parts','Use change control; test cause-and-effect and restore all protections']},
  {id:'drives',discipline:'Electrical',title:'VFDs, starters & protection',purpose:'Start, control and protect motors according to process demand.',inspect:['Fault history, current, DC bus and cooling fans','Parameters, contact condition and protection settings','Panel cleanliness, terminals and motor cable'],failures:['Overtemperature or fan failure','Supply disturbance/DC bus fault','Wrong settings, overload or motor/cable fault'],plan:['Back up parameters and record rating/firmware','Keep fan, keypad/control card or approved complete spare','Prove rotation, speed reference, interlocks and trips']}
];

export const plannerWorkflow=[
  ['1 · Understand duty','Confirm equipment function, operating conditions, criticality and consequence of failure.'],
  ['2 · Build failure picture','Review breakdown history, symptoms, failure modes, inspection trends and RCA actions.'],
  ['3 · Verify technical identity','Use equipment code, OEM model, drawing, part number, dimensions and material—not description alone.'],
  ['4 · Check spare readiness','Compare required quantity with store, open PR, open PO, lead time, repairability and interchangeability.'],
  ['5 · Prepare the job','Define scope, isolation/LOTOV, permits, manpower, tools, lifting, consumables, tolerances and acceptance checks.'],
  ['6 · Close and learn','Record measurements, replaced Material Codes, findings, photos, cause, recommendations and next due action.']
];
