import {materialRows,codeFrom,num,safeText} from '../services/materialQuery.js';
import {getMaterialImportHistory} from '../services/materialHistory.js';
import {getMaterialEvents} from '../services/materialEvents.js';
import {getProcurementHistory} from '../services/procurementEvents.js';
import {searchKnowledge} from '../services/knowledge.js';
import {getEquipmentKnowledge} from '../services/equipmentKnowledge.js';
import {getConsumptionStudy} from '../services/consumption.js';

const sapGlossary={material:'SAP Material Number / Material Code used to identify the material master record.','material no':'SAP Material Number / Material Code used to identify the material master record.',unrestricted:'Unrestricted-use stock currently available for normal issue/use.','purchase requisition':'PR document/request for procurement before a purchase order is created.','purchase req':'PR document/request for procurement before a purchase order is created.','open pr':'PR quantity still not converted/closed depending on the source report definition.','open po':'PO quantity still open / not fully delivered depending on the source report definition.','still to be delivered':'Open PO quantity still expected from the supplier.','order quantity':'Requested/order quantity in the source report; confirm report context before treating it as open PR.','name of supplier':'Supplier/Vendor name.','purchasing document':'Purchase Order document number in typical purchasing reports.','purchase requisition no':'Purchase Requisition document number.',plant:'SAP Plant organizational code.','base unit of measure':'Material master base UOM.','last issue date':'Most recent recorded goods issue date for the material in the report context.'};

const sapPlanner={
  material:{steps:['MM03 — Display Material','ZMMMATDTL / plant material-detail report when available'],tip:'Start with the exact Material Code. Verify description, UOM, purchasing and plant-specific views before planning.'},
  stock:{steps:['MMBE — Stock Overview','ZFGSTOCK / plant stock report when available','MB51 — Material movement history'],tip:'Use MMBE for current stock and MB51 when you need to understand how stock moved.'},
  movement:{steps:['MB51 — Material Document List'],tip:'Filter by Material Code, plant, posting date and movement type. Do not treat stock snapshots alone as consumption.'},
  pr:{steps:['ME5A — Purchase Requisitions','Plant PR report / planning export'],tip:'Confirm PR number, open quantity and whether the requirement has already been converted to PO.'},
  po:{steps:['ME2M — Purchase Orders by Material','ME2N — Purchase Orders by PO Number'],tip:'Check still-to-be-delivered/open quantity, vendor and expected delivery.'},
  equipment:{steps:['IE03 — Display Equipment','IL03 — Display Functional Location where used'],tip:'Use technical-object hierarchy to verify where the spare/equipment belongs.'},
  order:{steps:['IW33 — Display Maintenance Order','IW32 — Change Maintenance Order','IW42 — Confirmations where used by plant process'],tip:'Link the material requirement to the correct maintenance order/activity when planning work.'},
  notification:{steps:['IW23 — Display Notification'],tip:'Use notification history to understand the maintenance problem before choosing spares.'},
  maintenance_plan:{steps:['IP03 — Display Maintenance Plan','IP10 — Schedule Maintenance Plan','IP12 — Display Strategy where applicable'],tip:'Verify cycle/strategy and due packages before planning recurring spare demand.'}
};

export const toolDefinitions=[
  {type:'function',function:{name:'get_equipment_knowledge',description:'Get a planner-oriented overview of one equipment/sub-equipment: hierarchy, linked spares, critical/uncovered materials, documents and explicit component links when available. Use this when the user asks how equipment works, what they should learn, what spares belong to it, or asks for an equipment briefing.',parameters:{type:'object',properties:{equipment:{type:'string'},sub_equipment:{type:'string'},discipline:{type:'string'}},additionalProperties:false}}},
  {type:'function',function:{name:'find_material_code',description:'Find the best Material Code candidates for a spare/component description within the current equipment context. Return evidence from material name, description, part number and usage location rather than guessing a code.',parameters:{type:'object',properties:{query:{type:'string'},equipment:{type:'string'},sub_equipment:{type:'string'},limit:{type:'integer',minimum:1,maximum:10}},required:['query'],additionalProperties:false}}},
  {type:'function',function:{name:'get_material_profile',description:'Get the authoritative current profile for one spare by Material Code, including requirement, store, PR, PO, gap, locations and spare character.',parameters:{type:'object',properties:{material_code:{type:'string'}},required:['material_code'],additionalProperties:false}}},
  {type:'function',function:{name:'get_material_history',description:'Get dated material events when the structured event store is enabled, otherwise fall back to Excel/SAP import-change history. Never treat snapshots as consumption/failure history unless the source explicitly says so.',parameters:{type:'object',properties:{material_code:{type:'string'},limit:{type:'integer',minimum:1,maximum:50}},required:['material_code'],additionalProperties:false}}},
  {type:'function',function:{name:'get_material_consumption',description:'Get confirmed SAP goods-issue consumption for one Material Code, aggregated weekly or monthly for up to 120 months. Uses movement types 201/261/551 minus reversals 202/262. Inventory snapshots are excluded.',parameters:{type:'object',properties:{material_code:{type:'string'},period:{type:'string',enum:['week','month']},months:{type:'integer',minimum:1,maximum:120}},required:['material_code'],additionalProperties:false}}},
  {type:'function',function:{name:'get_procurement_history',description:'Get structured PR/PO/RGP/NRGP procurement events for one Material Code when procurement event storage is enabled. Use for document-level procurement timeline questions.',parameters:{type:'object',properties:{material_code:{type:'string'},limit:{type:'integer',minimum:1,maximum:100}},required:['material_code'],additionalProperties:false}}},
  {type:'function',function:{name:'search_knowledge',description:'Search uploaded manuals, OEM catalogues, datasheets, drawings, repair reports and other indexed engineering evidence. Use before making a document-specific/OEM-specific claim.',parameters:{type:'object',properties:{query:{type:'string'},material_code:{type:'string'},equipment:{type:'string'},sub_equipment:{type:'string'},discipline:{type:'string'},limit:{type:'integer',minimum:1,maximum:12}},required:['query'],additionalProperties:false}}},
  {type:'function',function:{name:'find_pr_eligible_spares',description:'Find spares whose current stock plus open PR plus open PO does not cover the recorded required quantity.',parameters:{type:'object',properties:{equipment:{type:'string'},sub_equipment:{type:'string'},discipline:{type:'string'},limit:{type:'integer',minimum:1,maximum:50}},additionalProperties:false}}},
  {type:'function',function:{name:'find_zero_stock_spares',description:'Find zero-stock spares, optionally only those without an open PO.',parameters:{type:'object',properties:{without_po:{type:'boolean'},equipment:{type:'string'},sub_equipment:{type:'string'},limit:{type:'integer',minimum:1,maximum:50}},additionalProperties:false}}},
  {type:'function',function:{name:'search_spares',description:'Search spare master data by material code fragment, spare name, description, part number or vendor.',parameters:{type:'object',properties:{search:{type:'string'},equipment:{type:'string'},sub_equipment:{type:'string'},limit:{type:'integer',minimum:1,maximum:50}},required:['search'],additionalProperties:false}}},
  {type:'function',function:{name:'get_procurement_justification_facts',description:'Get authoritative facts needed to draft a procurement justification for one material.',parameters:{type:'object',properties:{material_code:{type:'string'}},required:['material_code'],additionalProperties:false}}},
  {type:'function',function:{name:'calculate_three_phase_motor_current',description:'Estimate three-phase motor line current from kW, voltage, power factor and efficiency.',parameters:{type:'object',properties:{power_kw:{type:'number',exclusiveMinimum:0},voltage_v:{type:'number',exclusiveMinimum:0},power_factor:{type:'number',exclusiveMinimum:0,maximum:1},efficiency:{type:'number',exclusiveMinimum:0,maximum:1}},required:['power_kw','voltage_v','power_factor','efficiency'],additionalProperties:false}}},
  {type:'function',function:{name:'calculate_synchronous_speed',description:'Calculate AC motor synchronous speed from frequency and pole count.',parameters:{type:'object',properties:{frequency_hz:{type:'number',exclusiveMinimum:0},poles:{type:'integer',minimum:2,maximum:24}},required:['frequency_hz','poles'],additionalProperties:false}}},
  {type:'function',function:{name:'calculate_shaft_surface_speed',description:'Calculate shaft/cylindrical surface speed from diameter and RPM.',parameters:{type:'object',properties:{diameter_mm:{type:'number',exclusiveMinimum:0},rpm:{type:'number',minimum:0}},required:['diameter_mm','rpm'],additionalProperties:false}}},
  {type:'function',function:{name:'calculate_bearing_l10_life',description:'Estimate basic bearing L10 life using C, P and RPM.',parameters:{type:'object',properties:{dynamic_capacity_kn:{type:'number',exclusiveMinimum:0},equivalent_load_kn:{type:'number',exclusiveMinimum:0},rpm:{type:'number',exclusiveMinimum:0},bearing_type:{type:'string',enum:['ball','roller']}},required:['dynamic_capacity_kn','equivalent_load_kn','rpm','bearing_type'],additionalProperties:false}}},
  {type:'function',function:{name:'sap_field_help',description:'Explain common SAP material, stock, PR and PO report fields used by spare planners.',parameters:{type:'object',properties:{field_name:{type:'string'}},required:['field_name'],additionalProperties:false}}},
  {type:'function',function:{name:'sap_planner_guide',description:'Give a practical SAP HANA/SAP GUI planning path for material, stock, movements, PR, PO, equipment, work orders, notifications or maintenance plans. Use as planner guidance, not as proof of current SAP data.',parameters:{type:'object',properties:{task:{type:'string',enum:['material','stock','movement','pr','po','equipment','order','notification','maintenance_plan']}},required:['task'],additionalProperties:false}}}
];

export async function executeTool(name,args={},context={}){
  if(name==='get_equipment_knowledge')return getEquipmentKnowledge({...context,equipment:args.equipment||context.equipment,sub_equipment:args.sub_equipment||context.sub_equipment,discipline:args.discipline||context.discipline});
  if(name==='find_material_code')return {rows:await materialRows(context,{search:args.query,equipment:args.equipment||context.equipment,sub_equipment:args.sub_equipment||context.sub_equipment,limit:args.limit||8}),note:'These are candidates from current material master and usage locations. Do not invent a Material Code when no candidate is supported.'};
  if(name==='get_material_profile')return {rows:await materialRows(context,{material_code:args.material_code,limit:5})};
  if(name==='get_material_history'){
    const structured=await getMaterialEvents(args.material_code,args.limit||20);
    if(structured.enabled)return {...structured,source:'material_events',warning:'Inventory/PR/PO snapshots are not consumption or failure events.'};
    return {...await getMaterialImportHistory(args.material_code,args.limit||20),source:'import_history_fallback',note:structured.note};
  }
  if(name==='get_material_consumption')return getConsumptionStudy(args.material_code,{period:args.period||'month',months:args.months||24});
  if(name==='get_procurement_history')return {...await getProcurementHistory(args.material_code,args.limit||50),source:'procurement_events'};
  if(name==='search_knowledge')return {hits:await searchKnowledge(args.query,{...context,material_code:args.material_code||codeFrom(args.query),equipment:args.equipment||context.equipment,sub_equipment:args.sub_equipment||context.sub_equipment,discipline:args.discipline||context.discipline},args.limit||6)};
  if(name==='find_pr_eligible_spares')return {rows:await materialRows(context,{...args,pr_eligible:true,limit:args.limit||20})};
  if(name==='find_zero_stock_spares')return {rows:await materialRows(context,{...args,zero_stock:true,no_po:Boolean(args.without_po),limit:args.limit||20})};
  if(name==='search_spares')return {rows:await materialRows(context,{...args,search:args.search,limit:args.limit||20})};
  if(name==='get_procurement_justification_facts'){
    const rows=await materialRows(context,{material_code:args.material_code,limit:5}),history=await getProcurementHistory(args.material_code,20);
    return {rows,procurement_history:history,missing_evidence:['true consumption/issue history','lead time','unit price','failure history']};
  }
  if(name==='calculate_three_phase_motor_current'){const kw=num(args.power_kw),v=num(args.voltage_v),pf=num(args.power_factor),eff=num(args.efficiency);if(!(kw>0&&v>0&&pf>0&&pf<=1&&eff>0&&eff<=1))return {error:'Invalid motor inputs'};return {line_current_a:kw*1000/(Math.sqrt(3)*v*pf*eff),formula:'I = P/(sqrt(3) × V × PF × efficiency)',note:'Estimate only; verify nameplate current and applicable protection/cable standards before design use.'}}
  if(name==='calculate_synchronous_speed'){const f=num(args.frequency_hz),p=num(args.poles);if(!(f>0&&p>=2))return {error:'Invalid frequency or pole count'};return {synchronous_speed_rpm:120*f/p,formula:'Ns = 120f/p',note:'Actual induction motor running speed is lower because of slip.'}}
  if(name==='calculate_shaft_surface_speed'){const d=num(args.diameter_mm),rpm=num(args.rpm);if(!(d>0&&rpm>=0))return {error:'Invalid diameter or RPM'};return {surface_speed_m_s:Math.PI*(d/1000)*rpm/60,formula:'v = pi × D × RPM / 60'}}
  if(name==='calculate_bearing_l10_life'){const C=num(args.dynamic_capacity_kn),P=num(args.equivalent_load_kn),rpm=num(args.rpm),power=args.bearing_type==='roller'?10/3:3;if(!(C>0&&P>0&&rpm>0))return {error:'Invalid bearing inputs'};const revolutions_million=Math.pow(C/P,power),hours=revolutions_million*1e6/(60*rpm);return {l10_million_revolutions:revolutions_million,l10_hours:hours,exponent:power,note:'Basic rating life estimate only. Actual life depends on lubrication, contamination, alignment, temperature, load spectrum and mounting.'}}
  if(name==='sap_field_help'){const raw=safeText(args.field_name,120).toLowerCase(),key=Object.keys(sapGlossary).find(k=>raw===k||raw.includes(k));return {field:args.field_name,meaning:key?sapGlossary[key]:'No exact local glossary entry. Ask SAP report owner to confirm this field definition before using it in calculations.'}}
  if(name==='sap_planner_guide'){const guide=sapPlanner[args.task];return guide?{task:args.task,...guide,note:'Transaction availability/authorization can vary by plant and SAP configuration. Plant-specific Z transactions should be preferred when they are the approved local process.'}:{error:'Unknown SAP planning task'}}
  return {error:`Unknown tool: ${name}`};
}
