import React from 'react';
const Kpi=({n,t,onClick,tone=''})=><button className={`dashKpi ${tone}`} onClick={onClick} disabled={!onClick&&false}><span>{t}</span><strong>{n??0}</strong>{onClick&&<small>Open →</small>}</button>;
const disciplines=['Mechanical','Electrical','Instrumentation','Operation','Process','Common / Other'];
export default function Dashboard({stats,setTab,department,filters,setFilters,options}){
  const setEquipment=value=>setFilters(f=>({...f,area:'',equipment:value,sub_equipment:''}));
  const setDiscipline=value=>setFilters(f=>({...f,discipline:value}));
  const openProcurement=type=>{setFilters(f=>({...f,procurement_type:type}));setTab('Procurement')};
  const equipment=options.equipment_hierarchy?.length?options.equipment_hierarchy:(options.equipment||[]).map(name=>({name,code:''}));
  return <>
    <div className="pageTitle"><div><span className="eyebrow">PLANT SPARE INTELLIGENCE</span><h1>{department?.department_name||'Dashboard'}</h1><p>{department?.department_code||''} · Current spare coverage, procurement exposure and planner attention.</p></div></div>
    <div className="dashContext"><div><span>Equipment</span><div className="segmented"><button className={!filters.equipment?'active':''} onClick={()=>setEquipment('')}>All</button>{equipment.map(e=><button key={e.code||e.name} className={filters.equipment===e.name?'active':''} onClick={()=>setEquipment(e.name)}>{e.name}</button>)}</div></div><div><span>Discipline</span><div className="segmented"><button className={!filters.discipline?'active':''} onClick={()=>setDiscipline('')}>All</button>{disciplines.map(d=><button key={d} className={filters.discipline===d?'active':''} onClick={()=>setDiscipline(d)}>{d}</button>)}</div></div></div>
    <div className="dashKpis"><Kpi n={stats.total} t="Unique Materials"/><Kpi n={stats.available} t="Available in Store"/><Kpi n={stats.in_pr} t="Open PR" onClick={()=>openProcurement('pr')}/><Kpi n={stats.in_po} t="Open PO" onClick={()=>openProcurement('po')}/><Kpi n={stats.critical} t="Critical Spares" tone="warn" onClick={()=>setTab('Spare Intelligence')}/><Kpi n={stats.pr_eligible} t="PR Eligible" tone="danger" onClick={()=>setTab('Spare Intelligence')}/></div>
    <section className="dashActions"><div className="sectionHead"><div><h2>Planner actions</h2><p>Go directly to the workflow you need.</p></div></div><div className="dashActionGrid"><button onClick={()=>setTab('Spares')}><strong>Search spares</strong><span>Material master and current quantities</span></button><button onClick={()=>setTab('Equipment')}><strong>Browse equipment</strong><span>Grouped spare usage by sub-equipment</span></button><button onClick={()=>setTab('Spare Intelligence')}><strong>Review shortages</strong><span>Critical and PR-eligible materials</span></button><button onClick={()=>openProcurement('po')}><strong>Open PO</strong><span>Current PO coverage by Material Code</span></button><button onClick={()=>openProcurement('pr')}><strong>Open PR</strong><span>Current PR coverage by Material Code</span></button><button onClick={()=>setTab('Knowledge')}><strong>Plant Knowledge</strong><span>Manuals, OEM evidence and RAG search</span></button></div></section>
  </>;
}
