import React,{useEffect,useState} from 'react';
import ImportBox from '../components/ImportBox.jsx';
import AIImportAnalyzer from '../components/AIImportAnalyzer.jsx';
import UniversalImportInbox from '../components/UniversalImportInbox.jsx';
import DataReviewQueue from '../components/DataReviewQueue.jsx';
import {request} from '../api/client.js';

const disciplines=['','Mechanical','Electrical','Instrumentation','Operation','Process','Common / Other'];
const types={stock:{label:'Stock',text:'Updates Store Qty by existing Material Code.'},open_pr:{label:'Open PR',text:'Updates Open PR Qty by existing Material Code.'},open_po:{label:'Open PO',text:'Updates Open PO Qty and Vendor by existing Material Code.'},pr_planning:{label:'PR Planning',text:'Screens planning inputs without changing canonical quantities.',planning:true},rgp:{label:'RGP',text:'Maps returnable gate-pass data for review.',transaction:true},nrgp:{label:'NRGP',text:'Maps non-returnable gate-pass data for review.',transaction:true}};

export default function Imports({filters,options,reload,setNotice,refreshToken=0}){
  const[departmentCode,setDepartmentCode]=useState(filters.department_code||''),[area,setArea]=useState(filters.equipment||filters.area||''),[discipline,setDiscipline]=useState(filters.discipline||''),[areas,setAreas]=useState(options.equipment||options.areas||[]),[uploadType,setUploadType]=useState('open_po'),[undoing,setUndoing]=useState(null),[analyzedFile,setAnalyzedFile]=useState(null),[history,setHistory]=useState([]),[historyPage,setHistoryPage]=useState(1),[historyPaging,setHistoryPaging]=useState({page:1,page_size:25,total:0,pages:1}),[historyLoading,setHistoryLoading]=useState(false),[localRefresh,setLocalRefresh]=useState(0);
  useEffect(()=>{if(!departmentCode&&options.departments?.length)setDepartmentCode(options.departments[0].department_code)},[departmentCode,options.departments]);
  useEffect(()=>{if(!departmentCode)return;request('/options?'+new URLSearchParams({department_code:departmentCode})).then(x=>{const eq=x.equipment||x.areas||[];setAreas(eq);if(area&&!eq.includes(area))setArea('')}).catch(e=>setNotice(e.message))},[departmentCode]);
  const loadHistory=async(page=historyPage)=>{setHistoryLoading(true);try{const x=await request('/import-history/page?'+new URLSearchParams({page:String(page),page_size:'25'}));setHistory(x.rows||[]);setHistoryPaging(x.pagination||{page,page_size:25,total:(x.rows||[]).length,pages:1})}catch(e){setNotice(e.message)}finally{setHistoryLoading(false)}};
  useEffect(()=>{loadHistory(historyPage)},[historyPage,refreshToken,localRefresh]);
  const selectedDepartment=options.departments?.find(d=>d.department_code===departmentCode);
  const useMapping=({file,type})=>{if(['stock','open_pr','open_po','rgp','nrgp','pr_planning'].includes(type)){setUploadType(type);setAnalyzedFile(file)}else if(type==='master')setAnalyzedFile(file);else setNotice(`Unknown import type: ${type}`)};
  const refreshAll=async()=>{await reload();setLocalRefresh(x=>x+1);await loadHistory(historyPage)};
  const undo=async h=>{if(!confirm(`Undo import ${h.file_name}? Only unchanged values from this batch will be restored.`))return;setUndoing(h.id);try{const x=await request(`/import-history/${h.id}/rollback`,{method:'POST'});setNotice(`Undo complete: ${x.restored} materials restored${x.conflicts?.length?`, ${x.conflicts.length} conflicts skipped`:''}`);await refreshAll()}catch(e){setNotice(e.message)}finally{setUndoing(null)}};
  return <>
    <div className="pageTitle"><div><span className="eyebrow">DATA INGESTION</span><h1>Imports</h1><p>Upload once. Known SAP files use deterministic mapping; AI reviews semantics and unfamiliar structures without overriding trusted transaction rules.</p></div></div>

    <div className="importSteps"><div className="active"><b>1</b><span>Upload</span></div><div><b>2</b><span>Detect</span></div><div><b>3</b><span>Review</span></div><div><b>4</b><span>Commit</span></div></div>

    <section className="importContext"><div><strong>Import context</strong><span>Choose where this file belongs before analysis.</span></div><div className="importContextFields"><label>Sub-department<select value={departmentCode} onChange={e=>{setDepartmentCode(e.target.value);setArea('')}}>{(options.departments||[]).map(d=><option value={d.department_code} key={d.department_code}>{d.department_code} — {d.department_name}</option>)}</select></label><label>Equipment<select value={area} onChange={e=>setArea(e.target.value)}><option value="">All / not required</option>{areas.map(a=><option value={a} key={a}>{a}</option>)}</select></label><label>Discipline<select value={discipline} onChange={e=>setDiscipline(e.target.value)}>{disciplines.map(d=><option key={d||'blank'} value={d}>{d||'Read from Excel / blank'}</option>)}</select></label></div><div className="contextLine">{selectedDepartment?.department_code||departmentCode||'No department'}{area?` → ${area}`:''}{discipline?` · ${discipline}`:''}</div></section>

    <UniversalImportInbox departmentCode={departmentCode} equipment={area} discipline={discipline} reload={refreshAll} setNotice={setNotice}/>

    <section className="reviewSection"><div className="sectionHead"><div><h2>Human review</h2><p>Only batches with semantic warnings or exceptions need planner attention.</p></div></div><DataReviewQueue refreshToken={refreshToken+localRefresh} setNotice={setNotice}/></section>

    <details className="advancedImports"><summary>Advanced / compatibility import tools</summary><AIImportAnalyzer setNotice={setNotice} onUseMapping={useMapping}/><div className="importGrid"><div id="master-import"><ImportBox title="Full Spare Master" text="Compatibility master parser with no-code handling." preview="/import/master/preview" confirm="/import/master/confirm" departmentCode={departmentCode} area={area} requireArea showDiscipline initialFile={analyzedFile} reload={refreshAll} setNotice={setNotice}/></div><div id="typed-import"><div className="typePicker"><strong>Typed SAP / Procurement tool</strong><div>{Object.entries(types).map(([k,v])=><button type="button" key={k} className={uploadType===k?'active secondary':'secondary'} onClick={()=>setUploadType(k)}>{v.label}</button>)}</div></div>{types[uploadType].planning?<ImportBox key="pr_planning" title="PR Planning / Criticality Screen" text={types[uploadType].text} preview="/pr-planning/preview" confirm={null} departmentCode={departmentCode} area={area} initialFile={analyzedFile} reload={refreshAll} setNotice={setNotice}/>:types[uploadType].transaction?<div className="importBox"><h2>{types[uploadType].label} Import</h2><p>{types[uploadType].text}</p></div>:<ImportBox key={uploadType} title={`${types[uploadType].label} Update`} text={types[uploadType].text} preview="/import/sap/preview" confirm="/import/sap/confirm" uploadType={uploadType} departmentCode={departmentCode} initialFile={analyzedFile} reload={refreshAll} setNotice={setNotice}/>}</div></div></details>

    <details className="historyPanel"><summary>Import history · {historyPaging.total} batches</summary><div className="tableWrap"><table><thead><tr><th>Date</th><th>Type</th><th>File</th><th>Total</th><th>Added</th><th>Updated</th><th>Skipped</th><th>By</th><th></th></tr></thead><tbody>{history.map(h=>{const reversible=h.details?.changes?.length&&!h.details?.rolled_back_at;return <tr key={h.id}><td>{new Date(h.imported_at).toLocaleString()}</td><td>{(h.display_type||h.import_type).replaceAll('_',' ')}</td><td>{h.file_name}</td><td>{h.total_rows}</td><td>{h.added_rows}</td><td>{h.updated_rows}</td><td>{h.skipped_rows}</td><td>{h.imported_by_name||'—'}</td><td>{h.details?.rolled_back_at?<span className="muted">Undone</span>:reversible?<button className="link" disabled={undoing===h.id} onClick={()=>undo(h)}>Undo</button>:null}</td></tr>})}</tbody></table></div><div className="pagination"><span>{historyLoading?'Loading…':`Showing ${history.length} of ${historyPaging.total}`}</span><div><button className="secondary" disabled={historyLoading||historyPaging.page<=1} onClick={()=>setHistoryPage(x=>Math.max(1,x-1))}>Previous</button><span>Page {historyPaging.page} / {historyPaging.pages}</span><button className="secondary" disabled={historyLoading||historyPaging.page>=historyPaging.pages} onClick={()=>setHistoryPage(x=>Math.min(historyPaging.pages,x+1))}>Next</button></div></div></details>
  </>;
}
