import React,{useEffect,useState} from 'react';
import {request} from '../api/client.js';

const disciplines=['Mechanical','Electrical','Instrumentation','Operation','Process','Common / Other'];
const types=['Manual','OEM Catalogue','Datasheet','Drawing Notes','Repair Report','Failure / RCA','Procurement Justification','Other'];

export default function Knowledge({filters,canEdit,setNotice}){
  const[docs,setDocs]=useState([]),[paging,setPaging]=useState({page:1,page_size:25,total:0,pages:1}),[page,setPage]=useState(1),[status,setStatus]=useState(null),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[hits,setHits]=useState([]),[searching,setSearching]=useState(false),[loadingDocs,setLoadingDocs]=useState(false);
  const[form,setForm]=useState({title:'',document_type:'Manual',manufacturer:'',equipment:filters.equipment||'',sub_equipment:filters.sub_equipment||'',discipline:filters.discipline||'',material_code:'',notes:''});
  const loadDocs=async(target=page)=>{setLoadingDocs(true);try{const x=await request('/knowledge/page?'+new URLSearchParams({page:String(target),page_size:'25'}));setDocs(x.rows||[]);setPaging(x.pagination||{page:target,page_size:25,total:(x.rows||[]).length,pages:1})}catch(e){setNotice(e.message)}finally{setLoadingDocs(false)}};
  useEffect(()=>{loadDocs(page)},[page]);useEffect(()=>{request('/knowledge/status').then(setStatus).catch(e=>setNotice(e.message))},[]);
  useEffect(()=>setForm(f=>({...f,equipment:filters.equipment||f.equipment,sub_equipment:filters.sub_equipment||f.sub_equipment,discipline:filters.discipline||f.discipline})),[filters.equipment,filters.sub_equipment,filters.discipline]);
  const upload=async()=>{if(!file||busy)return;setBusy(true);try{const fd=new FormData();fd.append('file',file);fd.append('department_code',filters.department_code||'');for(const[k,v]of Object.entries(form))fd.append(k,v||'');const x=await request('/knowledge/upload',{method:'POST',body:fd});setNotice(`${x.title} indexed: ${x.chunks} chunks.`);setFile(null);setForm(f=>({...f,title:'',manufacturer:'',material_code:'',notes:''}));setPage(1);await loadDocs(1)}catch(e){setNotice(e.message)}finally{setBusy(false)}};
  const search=async()=>{if(!query.trim())return;setSearching(true);try{const x=await request('/knowledge/search',{method:'POST',body:JSON.stringify({query,context:{department_code:filters.department_code,equipment:filters.equipment,sub_equipment:filters.sub_equipment,discipline:filters.discipline},limit:8})});setHits(x.hits||[])}catch(e){setNotice(e.message)}finally{setSearching(false)}};
  return <>
    <div className="pageTitle"><div><span className="eyebrow">ENGINEERING MEMORY</span><h1>Plant Knowledge</h1><p>Search manuals, OEM catalogues, repair reports and engineering evidence used by Copilot and Reliability tools.</p></div></div>

    <div className="knowledgeHero"><div><strong>{paging.total}</strong><span>Indexed documents</span></div><div><strong>{status?.structuredStore?'Structured RAG':'Legacy RAG'}</strong><span>Knowledge store</span></div><div><strong>{status?.objectStorage?.configured?'Archived':'Text only'}</strong><span>Original files</span></div></div>

    <section className="knowledgeSearch"><div><h2>Search plant knowledge</h2><p>Ask an engineering question. Results are scoped by the current CH2 context where possible.</p></div><div className="knowledgeSearchBar"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}} placeholder="e.g. recommended lubrication for finishing mill bearing"/><button disabled={!query.trim()||searching} onClick={search}>{searching?'Searching…':'Search'}</button></div>{hits.length>0&&<div className="knowledgeHits">{hits.map((h,i)=><article key={`${h.document_id}-${h.chunk_index}-${i}`}><div><strong>{h.metadata?.title||h.file_name}</strong><span>{[h.metadata?.document_type,h.metadata?.manufacturer,h.metadata?.equipment,h.metadata?.sub_equipment].filter(Boolean).join(' · ')}</span></div><p>{h.text}</p><small>Evidence chunk #{Number(h.chunk_index)+1} · score {h.score}</small></article>)}</div>}</section>

    {canEdit&&<details className="knowledgeUpload"><summary>Add engineering document</summary><div className="formGrid"><label>Document<input type="file" accept=".pdf,.txt,text/plain,application/pdf" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(f&&!form.title)setForm(x=>({...x,title:f.name.replace(/\.[^.]+$/,'')}))}}/></label><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Document Type<select value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>Manufacturer / OEM<input value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></label><label>Equipment<input value={form.equipment} onChange={e=>setForm({...form,equipment:e.target.value})}/></label><label>Sub-equipment<input value={form.sub_equipment} onChange={e=>setForm({...form,sub_equipment:e.target.value})}/></label><label>Discipline<select value={form.discipline} onChange={e=>setForm({...form,discipline:e.target.value})}><option value="">Any / mixed</option>{disciplines.map(x=><option key={x}>{x}</option>)}</select></label><label>Related Material Code<input className="code" value={form.material_code} onChange={e=>setForm({...form,material_code:e.target.value.toUpperCase()})} placeholder="Optional"/></label></div><div className="actions"><button disabled={!file||busy} onClick={upload}>{busy?'Indexing…':'Index Document'}</button></div></details>}

    <section><div className="sectionHead"><div><h2>Knowledge archive</h2><p>Indexed evidence available to RAG and Copilot.</p></div></div><div className="tableWrap"><table><thead><tr><th>Title</th><th>Type</th><th>OEM</th><th>Equipment</th><th>Discipline</th><th>Material Code</th><th>Chunks</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><strong>{d.title||d.file_name}</strong><small className="muted block">{new Date(d.imported_at).toLocaleDateString()}</small></td><td>{d.document_type||'—'}</td><td>{d.manufacturer||'—'}</td><td>{[d.equipment,d.sub_equipment].filter(Boolean).join(' → ')||'—'}</td><td>{d.discipline||'—'}</td><td className="code">{d.material_code||'—'}</td><td>{d.chunks}</td></tr>)}</tbody></table></div><div className="pagination"><span>{loadingDocs?'Loading…':`Showing ${docs.length} of ${paging.total} documents`}</span><div><button className="secondary" disabled={loadingDocs||paging.page<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>Previous</button><span>Page {paging.page} / {paging.pages}</span><button className="secondary" disabled={loadingDocs||paging.page>=paging.pages} onClick={()=>setPage(x=>Math.min(paging.pages,x+1))}>Next</button></div></div></section>
  </>;
}
