import React,{useEffect,useState} from 'react';
import {request} from '../api/client.js';

const types=['Manual','OEM Catalogue','Datasheet','Drawing Notes','Repair Report','Failure / RCA','Other'];

export default function Knowledge({filters,canEdit,setNotice}){
  const[docs,setDocs]=useState([]),[paging,setPaging]=useState({page:1,page_size:12,total:0,pages:1}),[page,setPage]=useState(1),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[hits,setHits]=useState([]),[searching,setSearching]=useState(false);
  const[form,setForm]=useState({title:'',document_type:'Manual',material_code:''});
  const loadDocs=async(target=page)=>{try{const x=await request('/knowledge/page?'+new URLSearchParams({page:String(target),page_size:'12'}));setDocs(x.rows||[]);setPaging(x.pagination||{page:target,page_size:12,total:0,pages:1})}catch(e){setNotice(e.message)}};
  useEffect(()=>{loadDocs(page)},[page]);
  const upload=async()=>{if(!file||busy)return;setBusy(true);try{const fd=new FormData();fd.append('file',file);fd.append('department_code',filters.department_code||'');fd.append('equipment',filters.equipment||'');fd.append('sub_equipment',filters.sub_equipment||'');fd.append('discipline',filters.discipline||'');fd.append('title',form.title||file.name.replace(/\.[^.]+$/,''));fd.append('document_type',form.document_type);fd.append('material_code',form.material_code||'');const x=await request('/knowledge/upload',{method:'POST',body:fd});setNotice(`${x.title} added to Plant Knowledge.`);setFile(null);setForm({title:'',document_type:'Manual',material_code:''});setPage(1);await loadDocs(1)}catch(e){setNotice(e.message)}finally{setBusy(false)}};
  const search=async()=>{if(!query.trim())return;setSearching(true);try{const x=await request('/knowledge/search',{method:'POST',body:JSON.stringify({query,context:{department_code:filters.department_code,equipment:filters.equipment,sub_equipment:filters.sub_equipment,discipline:filters.discipline},limit:8})});setHits(x.hits||[])}catch(e){setNotice(e.message)}finally{setSearching(false)}};
  return <>
    <div className="pageTitle"><div><span className="eyebrow">PLANT KNOWLEDGE</span><h1>Search engineering knowledge</h1><p>Manuals, OEM documents, repair reports and plant evidence available to Copilot.</p></div></div>

    <section className="knowledgeSearch simpleKnowledgeSearch"><div className="knowledgeSearchBar"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}} placeholder="Ask about a spare, equipment, lubrication, failure or OEM recommendation…"/><button disabled={!query.trim()||searching} onClick={search}>{searching?'Searching…':'Search'}</button></div>{hits.length>0&&<div className="knowledgeHits">{hits.map((h,i)=><article key={`${h.document_id}-${h.chunk_index}-${i}`}><strong>{h.metadata?.title||h.file_name}</strong><p>{h.text}</p><small>{[h.metadata?.document_type,h.metadata?.equipment,h.metadata?.sub_equipment].filter(Boolean).join(' · ')}</small></article>)}</div>}</section>

    {canEdit&&<section className="simpleKnowledgeUpload"><div><h2>Add document</h2><p>Current equipment and discipline context will be attached automatically.</p></div><div className="knowledgeUploadRow"><label className="simpleFile"><span>{file?file.name:'Choose PDF or text file'}</span><input type="file" accept=".pdf,.txt,text/plain,application/pdf" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(f&&!form.title)setForm(x=>({...x,title:f.name.replace(/\.[^.]+$/,'')}))}}/></label><input placeholder="Title (optional)" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select><input className="code" placeholder="Related Material Code (optional)" value={form.material_code} onChange={e=>setForm({...form,material_code:e.target.value.toUpperCase()})}/><button disabled={!file||busy} onClick={upload}>{busy?'Adding…':'Add to Knowledge'}</button></div><small>{filters.department_code}{filters.equipment?` → ${filters.equipment}`:''}{filters.sub_equipment?` → ${filters.sub_equipment}`:''}{filters.discipline?` · ${filters.discipline}`:''}</small></section>}

    <section className="recentKnowledge"><div className="sectionHead"><div><h2>Recent documents</h2><p>{paging.total} documents indexed.</p></div></div><div className="knowledgeDocGrid">{docs.map(d=><article key={d.id}><span>{d.document_type||'Document'}</span><strong>{d.title||d.file_name}</strong><p>{[d.equipment,d.sub_equipment,d.discipline].filter(Boolean).join(' · ')||'General plant knowledge'}</p>{d.material_code&&<code>{d.material_code}</code>}</article>)}</div><div className="pagination"><span>Showing {docs.length} of {paging.total}</span><div><button className="secondary" disabled={paging.page<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>Previous</button><span>Page {paging.page} / {paging.pages}</span><button className="secondary" disabled={paging.page>=paging.pages} onClick={()=>setPage(x=>Math.min(paging.pages,x+1))}>Next</button></div></div></section>
  </>;
}
