import React,{useEffect,useState} from 'react';
import {request} from '../api/client.js';

const disciplines=['Mechanical','Electrical','Instrumentation','Operation','Process','Common / Other'];
const types=['Manual','OEM Catalogue','Datasheet','Drawing Notes','Repair Report','Failure / RCA','Procurement Justification','Other'];

export default function Knowledge({filters,options,canEdit,setNotice}){
  const[docs,setDocs]=useState([]),[status,setStatus]=useState(null),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[hits,setHits]=useState([]),[searching,setSearching]=useState(false);
  const[form,setForm]=useState({title:'',document_type:'Manual',manufacturer:'',equipment:filters.equipment||'',sub_equipment:filters.sub_equipment||'',discipline:filters.discipline||'',material_code:'',notes:''});
  const load=()=>Promise.all([request('/knowledge'),request('/knowledge/status')]).then(([d,s])=>{setDocs(d);setStatus(s)}).catch(e=>setNotice(e.message));
  useEffect(()=>{load()},[]);
  useEffect(()=>setForm(f=>({...f,equipment:filters.equipment||f.equipment,sub_equipment:filters.sub_equipment||f.sub_equipment,discipline:filters.discipline||f.discipline})),[filters.equipment,filters.sub_equipment,filters.discipline]);
  const upload=async()=>{if(!file||busy)return;setBusy(true);try{const fd=new FormData();fd.append('file',file);fd.append('department_code',filters.department_code||'');for(const[k,v]of Object.entries(form))fd.append(k,v||'');const x=await request('/knowledge/upload',{method:'POST',body:fd});setNotice(`${x.title} indexed: ${x.chunks} knowledge chunks. Original file archive: ${x.originalArchived?'yes':'not yet'}.`);setFile(null);setForm(f=>({...f,title:'',manufacturer:'',material_code:'',notes:''}));await load()}catch(e){setNotice(e.message)}finally{setBusy(false)}};
  const search=async()=>{if(!query.trim())return;setSearching(true);try{const x=await request('/knowledge/search',{method:'POST',body:JSON.stringify({query,context:{department_code:filters.department_code,equipment:filters.equipment,sub_equipment:filters.sub_equipment,discipline:filters.discipline},limit:8})});setHits(x.hits||[])}catch(e){setNotice(e.message)}finally{setSearching(false)}};
  const storeLabel=status?.structuredStore?'Structured RAG':'Legacy RAG';
  const archiveLabel=status?.objectStorage?.configured?'Object storage':'Text only';
  return <>
    <div className="pageTitle"><div><h1>Knowledge Memory</h1><p>Manuals, catalogues and engineering evidence for RAG. Structured SAP/Excel data stays separate and authoritative.</p></div></div>
    <div className="cards"><div className="card"><strong>{docs.length}</strong><span>Indexed documents</span></div><div className="card"><strong>{docs.reduce((n,d)=>n+(Number(d.chunks)||0),0)}</strong><span>Searchable chunks</span></div><div className="card"><strong>{storeLabel}</strong><span>{status?.structuredStore?'Document + chunk tables':'Backward-compatible JSON store'}</span></div><div className="card"><strong>{archiveLabel}</strong><span>{status?.objectStorage?.configured?`${status.objectStorage.provider} · ${status.objectStorage.bucket||'private bucket'}`:'Raw binary archive not configured'}</span></div></div>
    {canEdit&&<section className="importBox"><h2>Knowledge Inbox</h2><p>Upload PDF or text. Tagging improves retrieval for Mechanical, Electrical and Reliability agents.</p><div className="formGrid"><label>Document<input type="file" accept=".pdf,.txt,text/plain,application/pdf" onChange={e=>{const f=e.target.files?.[0]||null;setFile(f);if(f&&!form.title)setForm(x=>({...x,title:f.name.replace(/\.[^.]+$/,'')}))}}/></label><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Document Type<select value={form.document_type} onChange={e=>setForm({...form,document_type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>Manufacturer / OEM<input value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></label><label>Equipment<input value={form.equipment} onChange={e=>setForm({...form,equipment:e.target.value})} placeholder="WRM"/></label><label>Sub-equipment<input value={form.sub_equipment} onChange={e=>setForm({...form,sub_equipment:e.target.value})} placeholder="Finishing Mill"/></label><label>Discipline<select value={form.discipline} onChange={e=>setForm({...form,discipline:e.target.value})}><option value="">Any / mixed</option>{disciplines.map(x=><option key={x}>{x}</option>)}</select></label><label>Related Material Code<input className="code" value={form.material_code} onChange={e=>setForm({...form,material_code:e.target.value.toUpperCase()})} placeholder="Optional"/></label></div><label className="block">Notes<input style={{width:'100%',height:42,marginTop:6,border:'1px solid #d5dce8',borderRadius:8,padding:'0 11px'}} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="actions"><button disabled={!file||busy} onClick={upload}>{busy?'Extracting & indexing…':'Index Document'}</button></div></section>}
    <section><h2>Search engineering knowledge</h2><div className="procFilters"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')search()}} placeholder="e.g. recommended bearing lubrication for finishing mill motor"/><button disabled={!query.trim()||searching} onClick={search}>{searching?'Searching…':'Search Knowledge'}</button></div>{hits.length>0&&<div className="listCards">{hits.map((h,i)=><div className="card" key={`${h.document_id}-${h.chunk_index}-${i}`}><strong>{h.metadata?.title||h.file_name}</strong><span>{[h.metadata?.document_type,h.metadata?.manufacturer,h.metadata?.equipment,h.metadata?.sub_equipment,h.metadata?.discipline].filter(Boolean).join(' · ')}</span><p style={{fontSize:13,lineHeight:1.5}}>{h.text}</p><small>Evidence chunk #{Number(h.chunk_index)+1} · score {h.score}</small></div>)}</div>}</section>
    <section><h2>Indexed documents</h2><div className="tableWrap"><table><thead><tr><th>Date</th><th>Title</th><th>Type</th><th>OEM</th><th>Equipment</th><th>Discipline</th><th>Material Code</th><th>Chunks</th><th>Raw Archive</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{new Date(d.imported_at).toLocaleString()}</td><td>{d.title||d.file_name}</td><td>{d.document_type||'—'}</td><td>{d.manufacturer||'—'}</td><td>{[d.equipment,d.sub_equipment].filter(Boolean).join(' → ')||'—'}</td><td>{d.discipline||'—'}</td><td className="code">{d.material_code||'—'}</td><td>{d.chunks}</td><td>{d.originalArchived?'Archived':'Text only'}</td></tr>)}</tbody></table></div></section>
  </>;
}
