import React,{useEffect,useMemo,useState} from 'react';
import {request} from '../api/client.js';

const labels={eligible:'PR Eligible',critical:'Critical',pr:'Open PR',po:'Open PO',rgp:'RGP',nrgp:'NRGP'};
export default function Procurement({filters,setFilters,setNotice}){
  const[type,setType]=useState(filters.procurement_type||'eligible'),[rows,setRows]=useState([]),[search,setSearch]=useState(''),[screening,setScreening]=useState([]),[screenBusy,setScreenBusy]=useState(false),[screenSource,setScreenSource]=useState(''),[page,setPage]=useState(1),[paging,setPaging]=useState({page:1,page_size:50,total:0,pages:1}),[loading,setLoading]=useState(false);
  useEffect(()=>{if(filters.procurement_type&&filters.procurement_type!==type)setType(filters.procurement_type)},[filters.procurement_type]);
  const chooseType=t=>{setType(t);setPage(1);setScreening([]);setScreenSource('');setFilters?.(f=>({...f,procurement_type:t}))};
  const liveType=['eligible','critical','pr','po'].includes(type);
  const queryKey=JSON.stringify({department_code:filters.department_code||'',area:filters.area||'',type,search});
  useEffect(()=>{setPage(1)},[queryKey]);
  useEffect(()=>{if(!liveType){setRows([]);setPaging({page:1,page_size:50,total:0,pages:1});return;}setLoading(true);const qs=new URLSearchParams({department_code:filters.department_code||'',area:filters.area||'',type,search,page:String(page),page_size:'50'});request('/procurement?'+qs).then(x=>{setRows(x.rows||[]);setPaging(x.pagination||{page,page_size:50,total:(x.rows||[]).length,pages:1})}).catch(e=>setNotice(e.message)).finally(()=>setLoading(false))},[filters.department_code,filters.area,type,search,page]);
  const rankMap=useMemo(()=>new Map(screening.map(x=>[x.material_code,x])),[screening]);
  const aiScreen=async()=>{setScreenBusy(true);try{const x=await request('/procurement/pr-eligible/screen',{method:'POST',body:JSON.stringify({department_code:filters.department_code||'',area:filters.area||'',search})});setScreening(x.screening||[]);setScreenSource(x.source||'');setNotice(x.message)}catch(e){setNotice(e.message)}finally{setScreenBusy(false)}};
  const criticalView=type==='eligible'||type==='critical';
  return <>
    <div className="pageTitle"><div><span className="eyebrow">PROCUREMENT WORKSPACE</span><h1>{labels[type]}</h1><p>Current procurement coverage matched to the existing material master by Material Code.</p></div><div className="pageMeta"><strong>{paging.total||0}</strong><span>matching materials</span></div></div>
    <div className="procWorkspaceBar"><div className="segmented procSegments">{Object.entries(labels).map(([k,l])=><button key={k} className={type===k?'active':''} onClick={()=>chooseType(k)}>{l}</button>)}</div>{liveType&&<div className="procSearch"><input placeholder="Search material, spare or vendor…" value={search} onChange={e=>setSearch(e.target.value)}/>{type==='eligible'&&<button onClick={aiScreen} disabled={screenBusy}>{screenBusy?'Reviewing…':'AI prioritise'}</button>}</div>}</div>
    {type==='eligible'&&<div className="intelAiNote"><strong>Rule authority</strong><span>PR eligibility is calculated from Required, Store, Open PR and Open PO. AI can rank urgency and explain the result, but cannot change quantities.{screenSource?` Ranking source: ${screenSource}.`:''}</span></div>}
    {liveType?<><div className="tableWrap procurementTable"><table><thead><tr>{criticalView?<><th>Material</th><th>Required</th><th>Store</th><th>Open PR</th><th>Open PO</th><th>Gap</th><th>Priority</th><th>Vendor</th></>:<><th>Material</th><th>{type==='pr'?'Open PR Qty':'Open PO Qty'}</th><th>Vendor</th></>}</tr></thead><tbody>{rows.map(r=>{const screened=rankMap.get(r.material_code);return criticalView?<tr key={r.id}><td><span className="code">{r.material_code||'—'}</span><strong className="tableTitle">{r.spare_name||'Unnamed spare'}</strong></td><td>{r.required_qty??'—'}</td><td>{r.store_qty??'—'}</td><td>{r.pr_qty??'—'}</td><td>{r.po_qty??'—'}</td><td><strong>{r.ideal_pr_qty??0}</strong></td><td><span className={String(screened?.priority||r.rule_priority||'').toLowerCase().includes('high')?'statusPill dangerPill':'statusPill warnPill'} title={screened?.reason||r.rule_reason||''}>{screened?.priority||r.rule_priority||'Review'}</span></td><td>{r.vendor||'—'}</td></tr>:<tr key={r.id}><td><span className="code">{r.material_code||'—'}</span><strong className="tableTitle">{r.spare_name||'Unnamed spare'}</strong></td><td><strong>{type==='pr'?(r.pr_qty??'—'):(r.po_qty??'—')}</strong></td><td>{r.vendor||'—'}</td></tr>})}</tbody></table></div><div className="pagination"><span>{loading?'Loading…':`Showing ${rows.length} of ${paging.total}`}</span><div><button className="secondary" disabled={loading||paging.page<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>Previous</button><span>Page {paging.page} / {paging.pages}</span><button className="secondary" disabled={loading||paging.page>=paging.pages} onClick={()=>setPage(x=>Math.min(paging.pages,x+1))}>Next</button></div></div></>:<div className="emptyState"><h3>{labels[type]}</h3><p>Transaction-level {labels[type]} history will appear here once its dedicated event feed is active.</p></div>}
  </>;
}
