import React,{useEffect,useMemo,useState} from 'react';
import {request} from '../api/client.js';

const Card=({n,t})=><div className="card"><strong>{n??0}</strong><span>{t}</span></div>;
const fmtDate=v=>v?new Date(v).toLocaleDateString():'—';

export default function SpareIntelligence({filters,options,setNotice}){
  const[status,setStatus]=useState('pr_eligible'),[search,setSearch]=useState(''),[data,setData]=useState({rows:[],summary:{}}),[busy,setBusy]=useState(false),[reviews,setReviews]=useState([]),[aiNote,setAiNote]=useState('');
  const[question,setQuestion]=useState(''),[assistantBusy,setAssistantBusy]=useState(false),[assistant,setAssistant]=useState(null);
  const qs=useMemo(()=>new URLSearchParams({department_code:filters.department_code||'',area:filters.area||'',discipline:filters.discipline||'',status,search}),[filters.department_code,filters.area,filters.discipline,status,search]);
  useEffect(()=>{if(!filters.department_code)return;request('/spare-intelligence?'+qs).then(x=>{setData(x);setReviews([]);setAiNote('')}).catch(e=>setNotice(e.message))},[String(qs)]);
  const review=async()=>{const items=(data.rows||[]).slice(0,25);if(!items.length)return;setBusy(true);try{const x=await request('/spare-intelligence/review',{method:'POST',body:JSON.stringify({items})});setReviews(x.reviews||[]);setAiNote(x.note|| (x.aiEnabled?'AI review complete':'Rule-based review complete'))}catch(e){setNotice(e.message)}finally{setBusy(false)}};
  const ask=async e=>{e?.preventDefault();if(!question.trim())return;setAssistantBusy(true);setAssistant(null);try{const x=await request('/spare-assistant/ask',{method:'POST',body:JSON.stringify({question,department_code:filters.department_code})});setAssistant(x)}catch(e){setNotice(e.message)}finally{setAssistantBusy(false)}};
  const reviewMap=new Map((reviews||[]).map(x=>[x.material_code,x]));
  return <>
    <div className="pageTitle"><div><h1>Spare Intelligence</h1><p>Rules calculate shortage and PR eligibility. AI explains and prioritizes from plant data; it cannot change SAP quantities.</p></div><button disabled={busy||!data.rows?.length} onClick={review}>{busy?'Reviewing...':'AI Review Top 25'}</button></div>

    <section className="assistantPanel">
      <div><h2>AI Spare Assistant</h2><p className="muted">Ask only about spare planning, stock, PR/PO coverage, spare character or procurement justification. Answers are grounded in dashboard data.</p></div>
      <form onSubmit={ask} className="assistantAsk"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask: Why is MMT311715050461 critical?"/><button disabled={assistantBusy||!question.trim()}>{assistantBusy?'Checking...':'Ask Assistant'}</button></form>
      <div className="chipRow"><button type="button" className="chip" onClick={()=>setQuestion('Show zero-stock spares without PO')}>Zero stock without PO</button><button type="button" className="chip" onClick={()=>setQuestion('Which materials are PR eligible?')}>PR eligible</button><button type="button" className="chip" onClick={()=>setQuestion('Draft procurement justification for the highest risk spare')}>Draft justification</button></div>
      {assistant&&<div className="aiResult"><div className="aiSummary"><span className={assistant.aiEnabled?'mapped':'unmapped'}>{assistant.aiEnabled?'AI grounded answer':'Rule-based answer'}</span>{assistant.note&&<small>{assistant.note}</small>}</div><div className="assistantAnswer">{String(assistant.answer||'').split('\n').map((line,i)=><p key={i}>{line}</p>)}</div></div>}
    </section>

    <div className="cards"><Card n={data.summary?.total} t="Materials screened"/><Card n={data.summary?.critical} t="Critical spares"/><Card n={data.summary?.pr_eligible} t="PR eligible"/><Card n={data.summary?.covered} t="Covered by stock/PR/PO"/><Card n={data.summary?.history_ready} t="With recorded history"/></div>
    <div className="filterSection"><strong>Status</strong><div className="chipRow">{[['all','All'],['critical','Critical'],['pr_eligible','PR Eligible'],['covered','Covered']].map(([k,l])=><button key={k} className={status===k?'chip activeChip':'chip'} onClick={()=>setStatus(k)}>{l}</button>)}</div></div>
    <div className="intelligenceFilters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search Material Code, spare, vendor..."/><select value={filters.equipment||''} disabled><option>{filters.equipment||'All Equipment'}</option></select><select value={filters.discipline||''} disabled><option>{filters.discipline||'All Disciplines'}</option></select></div>
    {aiNote&&<div className="hierarchyBanner"><strong>{aiNote}</strong></div>}
    <div className="tableWrap"><table><thead><tr><th>Risk</th><th>Material Code</th><th>Spare / Character</th><th>Required</th><th>Store</th><th>PR</th><th>PO</th><th>Gap / Ideal PR</th><th>History</th><th>Locations</th><th>Status</th><th>Review</th></tr></thead><tbody>{(data.rows||[]).map(x=>{const r=reviewMap.get(x.material_code);return <tr key={x.material_code}><td><span className={Number(x.risk_score)>=80?'riskBadge highRisk':Number(x.risk_score)>=50?'riskBadge mediumRisk':'riskBadge'}>{x.risk_score}</span></td><td className="code">{x.material_code}</td><td><strong>{x.spare_name||'—'}</strong><small className="muted block">{x.description||''}</small><small className="characterTag">{x.spare_character}</small></td><td>{x.required_qty??0}</td><td>{x.store_qty??0}</td><td>{x.pr_qty??0}</td><td>{x.po_qty??0}</td><td><strong>{x.ideal_pr_qty??0}</strong><small className="muted block">Pipeline {x.pipeline_qty??0}</small></td><td><strong>{x.history_updates??0} updates</strong><small className="muted block">Stock {x.stock_updates??0} · PR {x.pr_updates??0} · PO {x.po_updates??0}</small><small className="muted block">Last {fmtDate(x.last_history_update)}</small></td><td><span>{x.usage_count} use(s)</span><small className="muted block">{x.locations||'—'}</small></td><td>{x.pr_eligible?<span className="statusPill dangerPill">PR Eligible</span>:x.critical?<span className="statusPill warnPill">Critical</span>:<span className="statusPill okPill">Covered</span>}</td><td>{r?<><strong>{r.classification}</strong><small className="muted block">{r.reason}</small></>:<small>{x.rule_explanation}</small>}</td></tr>})}</tbody></table></div>
    <p className="muted">History counts are import/change events, not consumption. Once SAP consumption, last issue, lead time and price data are imported, those become separate planning signals on this same screen.</p>
  </>;
}
