import React,{useEffect,useState} from 'react';
import {request} from '../api/client.js';

const pretty=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const supported=new Set(['stock','open_pr','open_po']);

export default function UniversalImportInbox({departmentCode,equipment,discipline,reload,setNotice}){
  const[file,setFile]=useState(null),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[confirming,setConfirming]=useState(false),[gateway,setGateway]=useState(null);
  useEffect(()=>{request('/v1/plant/status').then(x=>setGateway({ready:Boolean(x.capabilities?.rawEvidenceStore&&x.reviewQueue?.enabled),status:x})).catch(()=>setGateway({ready:false,status:null}))},[]);
  const makeLegacyForm=()=>{const f=new FormData();f.append('file',file);f.append('department_code',departmentCode||'');f.append('area',equipment||'');f.append('discipline',discipline||'');return f};
  const makeGatewayForm=()=>{const f=new FormData();f.append('file',file);f.append('department_code',departmentCode||'');f.append('equipment',equipment||'');f.append('discipline',discipline||'');f.append('mode','review');return f};
  const normalizeGateway=x=>{const det=x.review?.deterministic||{},llm=x.review?.llm||{},type=x.canonical?.file_type||'unknown',canAuto=Boolean(x.canonical?.staged?.enabled&&det.writeAllowed&&llm.decision==='accept'&&supported.has(type));return {gateway:true,batchId:x.raw_store?.batch_id,fileType:type,totalRows:x.canonical?.rows||0,rows:x.canonical?.sample||[],aiEnabled:x.canonical?.ai_enabled,source:x.canonical?.source,rawStore:x.raw_store,deterministic:det,llm,writable:canAuto,needsHuman:Boolean(det.writeAllowed&&llm.decision!=='accept'),message:!det.writeAllowed?`Blocked by validation: ${det.summary||'hard validation failed'}`:llm.decision!=='accept'?`LLM semantic review is ${llm.decision}; batch is preserved for Human Review.`:supported.has(type)?'Raw evidence stored, deterministic validation passed and LLM semantic review accepted. Ready to commit this reviewed batch.':`${pretty(type)} is preserved/reviewed but not yet supported for canonical API commit.`};};
  const analyze=async()=>{if(!file)return;setBusy(true);setPreview(null);try{if(gateway?.ready){const x=await request('/v1/plant/excel',{method:'POST',body:makeGatewayForm()});setPreview(normalizeGateway(x))}else{const x=await request('/import/universal/preview',{method:'POST',body:makeLegacyForm()});setPreview(x)}}catch(e){setNotice(e.message)}finally{setBusy(false)}};
  const confirm=async()=>{if(!file||!preview?.writable)return;setConfirming(true);try{if(preview.gateway){const x=await request(`/v1/plant/reviews/${preview.batchId}/commit`,{method:'POST',body:JSON.stringify({})});if(x.needs_human_review){setNotice(x.message||'Batch moved to Human Review.')}else setNotice(`Reviewed batch committed: ${x.canonical_write?.updated||0} updated, ${x.canonical_write?.unchanged||0} unchanged.`)}else{const x=await request('/import/universal/confirm',{method:'POST',body:makeLegacyForm()});setNotice(`AI Import complete: ${x.added||0} added, ${x.updated||0} updated, ${x.unchanged||0} unchanged, ${x.skipped||0} skipped.`)}setPreview(null);setFile(null);await reload()}catch(e){setNotice(e.message)}finally{setConfirming(false)}};
  const det=preview?.deterministic,llm=preview?.llm;
  return <section className="universalInbox">
    <div className="universalInboxHead"><div><span className="aiBadge">AI-NATIVE IMPORT</span><h2>Drop any SAP / spare Excel</h2><p>{gateway?.ready?'Plant API gateway: raw evidence → canonical staging → deterministic validation → LLM review → commit/human review.':'Compatibility mode: raw-evidence/review migrations are not active yet. Existing Universal Import remains available until the Plant API gateway can be activated safely.'}</p></div><div className="universalInboxControls"><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null)}}/><button disabled={!file||busy} onClick={analyze}>{busy?'Understanding workbook…':gateway?.ready?'Store & Review File':'Understand File'}</button></div></div>
    {gateway&&!gateway.ready&&<div className="universalWarnings"><strong>Raw evidence gateway pending activation</strong><span>Current imports still work, but full Bronze/Silver retention begins automatically after database migrations 006/007 are safely applied.</span></div>}
    {file&&<div className="universalFile"><strong>{file.name}</strong><span>{departmentCode||'No sub-department'}{equipment?` → ${equipment}`:''}{discipline?` · ${discipline}`:' · Discipline not selected'}</span></div>}
    {preview&&<div className="universalPreview">
      <div className="universalStats"><div><small>Detected</small><strong>{pretty(preview.fileType)}</strong></div><div><small>Canonical rows</small><strong>{preview.totalRows}</strong></div>{preview.gateway?<><div><small>Hard rules</small><strong>{det?.decision||'—'}</strong></div><div><small>LLM review</small><strong>{llm?.decision||'—'}</strong></div><div><small>Raw evidence</small><strong>{preview.rawStore?.enabled?'Stored':'Unavailable'}</strong></div></>:<><div><small>Valid Material Codes</small><strong>{preview.validMaterialRows}</strong></div><div><small>Invalid / No Code</small><strong>{preview.invalidMaterialRows}</strong></div><div><small>Mapper</small><strong>{preview.aiEnabled?'LLM + validator':'Local + validator'}</strong></div></>}</div>
      {preview.gateway&&<><div className="fileHelp"><strong>Deterministic review</strong><span>{det?.summary||'—'}</span></div><div className="fileHelp"><strong>LLM semantic review{llm?.confidence!=null?` · ${Math.round(Number(llm.confidence)*100)}% confidence`:''}</strong><span>{llm?.summary||'—'}</span></div>{preview.rawStore?.batch_id&&<div className="universalFields"><strong>Evidence batch</strong><div><span>Batch #{preview.rawStore.batch_id}</span><span>{preview.rawStore.total_raw_rows} raw rows</span><span>{preview.rawStore.original_archived?'Original archived':'Rows stored in DB'}</span></div></div>}</>}
      {!preview.gateway&&preview.disciplineCounts&&<div className="universalFields"><strong>Discipline assignment</strong><div>{Object.entries(preview.disciplineCounts).map(([k,v])=><span key={k}>{k}: {v}</span>)}</div></div>}
      {((preview.issues||[]).length>0||det?.findings?.length>0||llm?.findings?.length>0)&&<div className="universalWarnings"><strong>Review findings</strong><span>{[...(preview.issues||[]).map(x=>x.reason),...(det?.findings||[]).map(x=>x.message),...(llm?.findings||[]).map(x=>x.message)].filter(Boolean).slice(0,5).join(' · ')}</span></div>}
      <div className="tableWrap universalTable"><table><thead><tr><th>Sheet</th><th>Row</th><th>Material Code</th><th>Spare Name</th><th>Discipline</th><th>Description</th><th>Required</th><th>Store</th><th>Open PR</th><th>Open PO</th></tr></thead><tbody>{(preview.rows||[]).slice(0,25).map((x,i)=><tr key={`${x.source_sheet}-${x.source_row}-${i}`}><td>{x.source_sheet}</td><td>{x.source_row}</td><td className="code">{x.material_code||'—'}</td><td>{x.spare_name||'—'}</td><td>{x.discipline||'—'}</td><td>{x.description||'—'}</td><td>{x.required_qty??'—'}</td><td>{x.store_qty??'—'}</td><td>{x.pr_qty??'—'}</td><td>{x.po_qty??'—'}</td></tr>)}</tbody></table></div>
      <div className="universalActions"><div><strong>{preview.writable?'Reviewed commit path available':preview.needsHuman?'Human review required':'Not ready to write'}</strong><span>{preview.message}</span></div><button disabled={!preview.writable||confirming} onClick={confirm}>{confirming?'Committing reviewed batch…':preview.gateway?'Commit Reviewed Batch':'Confirm Validated Import'}</button></div>
    </div>}
  </section>;
}
